CREATE PROC FI_SP_AltBeneficiario
   @NOME        VARCHAR(50),
    @CPF         VARCHAR(14),
    @Id          BIGINT,
    @IDCLIENTE   BIGINT
AS
BEGIN
	UPDATE BENEFICIARIOS 
	SET 
		NOME = @NOME, 
		CPF = @CPF,
		IDCLIENTE = @IDCLIENTE
	WHERE Id = @Id
END